version: '3.8'

services:
  email-redis:
    image: redis:7-alpine
    container_name: email-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  email-backend:
    build: ./email-service
    container_name: email-backend
    ports:
      - "3015:3015"
    env_file:
      - ./email-service/.env
    environment:
      - PORT=3015
      - REDIS_HOST=email-redis
      - REDIS_PORT=6379
      - DATABASE_PATH=/app/data/email_cache.db
      - NODE_ENV=production
    volumes:
      - email-data:/app/data
      - ./email-service/llm-config.json:/app/llm-config.json:ro
    depends_on:
      - email-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3015/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  email-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: email-frontend
    ports:
      - "3623:3623"
    environment:
      - VITE_API_URL=
    depends_on:
      - email-backend
    restart: unless-stopped

volumes:
  email-data:
    driver: local
  redis-data:
    driver: local